### ISSUE TITLE
Error: TypeError: window.__TAURI_IPC__ is not a function

### ISSUE THREAD

**Issue by MarcMouries** [JordanRobo/Course-Progress#1]
bun install 
bun run dev --open

the window opens. The top data visualization are displayed but below is this error:
Error: TypeError: window.__TAURI_IPC__ is not a function

**Comment by JordanRobo** [comment]
Hey Marc,

Sorry to hear, from the sounds of it and based on those two commands I'd say your issue stems from the fact that you are trying to run this in the browser and not as a Tauri Application.

Try running `bunx tauri dev` and see if that works for you.

Note: if this doesn't work ensure you have downloaded Rust and the build tools for your environment. You can find additional information [here](https://tauri.app/v1/guides/getting-started/prerequisites) .
